name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # ---------- Deploy Frontend to S3 ----------
    - name: Upload to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --delete
      env:
        AWS_S3_BUCKET: contact-form-s3-lambda
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_REGION: ap-south-1
        SOURCE_DIR: frontend

    # ---------- Deploy Lambda ----------
    - name: Zip Lambda
      run: |
        cd backend
        zip -r function.zip .

    - name: Update Lambda Function
      run: |
        aws lambda update-function-code \
          --function-name ContactFormFunction \
          --zip-file fileb://backend/function.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_REGION: ap-south-1
